apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/sandersonsa/nodejs-ts-basic.git
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest